// omg we do have a includes i didnt see this lmfao
#pragma once

#include "vars.h"
#include "Renderer/renderer.hpp"
#include "paths.h"
#include <Geode/Geode.hpp>
#include <Geode/modify/CCKeyboardDispatcher.hpp>
#include <Geode/modify/GJGameLevel.hpp>
#include <imgui-cocos.hpp>
#include <Geode/modify/MenuLayer.hpp>
#include <Geode/modify/GJBaseGameLayer.hpp>
#include <cmath>
#include <Geode/modify/PlayLayer.hpp>
#include <Geode/modify/PlayerObject.hpp>
#include <Geode/modify/CCDelayTime.hpp>
#include <vector>
#include <string>
#include <cstring>
#include <algorithm>
#include "GUI/gui.hpp"
#include <Geode/modify/CCScheduler.hpp>
#include "GUI/mobile/mobileUI.hpp"
#include <Geode/modify/CCDirector.hpp>
#include <Geode/modify/ShaderLayer.hpp>
#include <Geode/modify/EditLevelLayer.hpp>
#include <Geode/modify/LevelInfoLayer.hpp>
#include <Geode/modify/UILayer.hpp>
#include <Geode/modify/GameLevelManager.hpp>
#include <Geode/modify/GameStatsManager.hpp>
#include <Geode/modify/GameManager.hpp>
#include <Geode/modify/GameToolbox.hpp>
#include <Geode/modify/GhostTrailEffect.hpp>
#include <Geode/modify/RingObject.hpp>